# Generated by Django 3.0.7 on 2020-06-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
